### ISSUE TITLE
Have .required() as method on primitives

### ISSUE THREAD

**Issue by dertseha** [tillre/jski#2]
To specify the required fields on the object level introduces duplication (names) and contradicts the otherwise fluent interface.

I'd like to specify
jski.object({
  ver: jski.number().required().minimum(1)
});

**Comment by tillre** [comment]
You are right, this would make for a nicer api. But it is different in the spec and it only makes sense to have requried properties on an object and not anywhere else and should therefor not be callable. Im not going to deviate from the spec here.
